### ISSUE TITLE
Jake老师请教一些iOS开发中UI设计的问题

### ISSUE THREAD

**Issue by TengHuo** [JakeLin/iOSAnimationSample#1]
在iOS开发中在storyboard拖好了控件之后，如何将控件定制化自己在Sketch设计的样子？这些是用代码实现的吗？

**Comment by JakeLin** [comment]
这个在教材下有教的，都是storyboard上实现，视频录制完了，在做后期制作。

**Comment by TengHuo** [comment]
ok~谢谢Jake老师～
